apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc-task-3
  labels:
    app: task-3
spec:
  type: NodePort
  selector:
    app: task-3
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  